name: demo
description: An absolute bare-bones web app.
version: 1.0.0 #you can uncomment this line and adjust it with your current version 
homepage: https://www.example.com #if you have a homepage, uncomment this line and replace the link

environment:
  sdk: '>=2.12.0 <3.0.0' #updated to the latest stable SDK version

dependencies:
  # Uncomment the line below if you are using the 'path' package in your project
  # path: ^1.7.0
  # Add this line if you don't have in your code
  html: any
  http: ^0.13.3
  
dev_dependencies:
  build_runner: ^2.1.2 #updated to the latest version
  build_web_compilers: ^4.0.4 #updated to the latest version
  linter: ^1.7.2 #updated to the latest version
  lints: ^2.0.0
